### ISSUE TITLE
Tutorial of `@app.route('/')` with authentication

### ISSUE THREAD

**Issue by amirbtb** [goblet/goblet#113]
I'm trying to setup a Cloud Function with multiple routes. The endpoint must be private but I don't really know much about authentication in Google Cloud. 
I've spend a lot of time reading [Goblet docs Authentication Topic](https://anovis.github.io/goblet/docs/build/html/topics.html#authentication) and all mentioned Google Docs + intensive research but I'm not sure how I should proceed : Do I have to setup something else in GCP ? (IAP, 0Auth) ?

**Comment by anovis** [comment]
It depends what is making the request. The most common use case is either a service or user using a service account. In that case you would add the following to your goblet security definitions

```
     "securityDefinitions": {
                "service-account": {
                    "authorizationUrl": "",
                    "flow": "implicit",
                    "type": "oauth2",
                    "x-google-audiences": "SERVICE_ACCOUNT_NAME@PROJECT.iam.gserviceaccount.com",
                    "x-google-issuer": "SERVICE_ACCOUNT_NAME@PROJECT.iam.gserviceaccount.com",
                    "x-google-jwks_uri": "https://www.googleapis.com/robot/v1/metadata/x509/profile-service@premise-dev.iam.gserviceaccount.com"
                },
}
 ```               
 
 then you would generate a token with the service account and attach to your request  ```"Authorization: Bearer ${TOKEN}"```
 
another option if you are using firebase auth on a web or mobile frontend is to simply pass that token and configure your security definition using the firebase client id. 

```
 securityDefinitions:
    firebase:
      authorizationUrl: ""
      flow: "implicit"
      type: "oauth2"
      # Replace YOUR-PROJECT-ID with your project ID
      x-google-issuer: "https://securetoken.google.com/YOUR-PROJECT-ID"
      x-google-jwks_uri: "https://www.googleapis.com/service_accounts/v1/metadata/x509/securetoken@system.gserviceaccount.com"
      x-google-audiences: "YOUR-PROJECT-ID"
 ```
      
i haven't used the other methods, but they should work similarly with the only  difference being the token in the request Authorization header.
