### ISSUE TITLE
[Workflows]

### ISSUE THREAD

**Issue by anovis** [goblet/goblet#177]
Ability to generate [gcp workflow](https://cloud.google.com/workflows) yaml files from code 
```
@worfklow('name', step=1,...)
@route('xxxx')
def route_workflow_step):
...

@worfklow('name', step=1,...)
@route('/xxxx/{input}', method=get)
def route_workflow_step(inpit):
...

```
sample yaml 
```
- randomgen_function:
    call: http.get
    args:
        url: https://REGION-PROJECT_ID.cloudfunctions.net/randomgen
    result: randomgen_result
- multiply_function:
    call: http.post
    args:
        url: https://REGION-PROJECT_ID.cloudfunctions.net/multiply
        body:
            input: ${randomgen_result.body.random}
    result: multiply_result
- log_function:
    call: http.get
    args:
        url: https://api.mathjs.org/v4/
        query:
            expr: ${"log(" + string(multiply_result.body.multiplied) + ")"}
    result: log_result
- floor_function:
    call: http.post
    args:
        url: CLOUD_RUN_SERVICE_URL
        auth:
            type: OIDC
        body:
            input: ${log_result.body}
    result: floor_result
- return_result:
    return: ${floor_result}
  
```

https://cloud.google.com/workflows/docs/run/tutorial-cloud-run
