### ISSUE TITLE
[Openapispec] - error creating spec

### ISSUE THREAD

**Issue by anovis** [goblet/goblet#437]
looks like the new Gconfig is messing up the openapispec generation

```
securityDefinitions: !!python/object/new:goblet.config.GConfig
  state:
    config:
      service-account: &id001
        authorizationUrl: ''
        flow: implicit
        type: oauth2
      firebase: &id002
        authorizationUrl: ''
        flow: implicit
        type: oauth2
        x-google-jwks_uri: 
  dictitems:
    service-account: *id001
    firebase: *id002
```
